spring.application.name=subscription-manager

# ===============================
# DATASOURCE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/subscription_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# Flyway owns the schema ? Hibernate must not validate or alter it
spring.jpa.hibernate.ddl-auto=none

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration
spring.flyway.baseline-on-migrate=false

# Log levels for debug
logging.level.org.flywaydb=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Mostra as queries no console para debugarmos os indices e o N+1
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.org.springframework.modulith.events=DEBUG

# ==========================================
# KAFKA CONFIGURATION
# ==========================================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.auto-offset-reset=earliest


# ==========================================
# Product Params
# ==========================================
billing.retry.max-attempts=3
billing.retry.delay-hours=2
billing.retry.delay.enabled=false